config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "foods#index"
  devise_for :users
  resources :foods do
    resource :likes, only: [:create, :destroy]
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  validates :name, presence: true
  mount_uploader :image, ImageUploader

  def liked_by?(user)
    likes.any? { |like| like.user_id == user.id }
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :food
  validates :user_id, uniqueness: {
    scope: :food_id,
    message: "は同じ投稿に2回以上いいねはできません"
  }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :foods, dependent: :destroy
  has_many :likes, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[edit update destroy]

  def index
    @foods = Food.all.includes(:user, :likes)
  end

  def new
    @food = Food.new
  end

  def create
    food = current_user.foods.create!(food_params)
    redirect_to food
  end

  def show
    @food = Food.find(params[:id])
  end

  def edit; end

  def update
    @food.update!(food_params)
    redirect_to @food
  end

  def destroy
    @food.destroy!
    redirect_to root_path
  end

  private

  def food_params
    params.require(:food).permit(:name, :comment, :image)
  end

  def set_food
    @food = current_user.foods.find(params[:id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @food = Food.find(params[:food_id])
    current_user.likes.create!(food_id: @food.id)
  end

  def destroy
    @food = Food.find(params[:food_id])
    current_user.likes.find_by(food_id: @food.id).destroy!
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/foods/_dislike.html.erb
<%= link_to "☆", food_likes_path(food), method: :post, remote: true %>

app/views/foods/_food.html.erb
<div>
  <p>【メールアドレス】 <%= food.user.email %></p>
  <p>【料理名】 <%= food.name %></p>
  <p id="food-<%= food.id %>">
    <% if food.liked_by?(current_user) %>
      <%= render "like", food: food %>
    <% else %>
      <%= render "dislike", food: food %>
    <% end %>
  </p>
  <p>
    <%= link_to "詳細", food %>
    <% if current_user.id == food.user_id %>
      <%= link_to "編集", edit_food_path(food) %>
      <%= link_to "削除", food_path(food), method: :delete, data: { confirm: "削除しますか？" } %>
    <% end %>
  </p>
</div>
<hr>

app/views/foods/_form.html.erb
<%= form_with model: @food, local: true do |form| %>
  <p><%= form.label :name %> <%= form.text_field :name, required: true %></p>
  <p><%= form.file_field :image, accept: "image/jpg, image/gif, image/png" %></p>
  <p><%= form.label :comment %> <%= form.text_area :comment %></p>
  <p><%= form.submit "送信" %></p>
<% end %>

app/views/foods/_like.html.erb
<%= link_to "★", food_likes_path(food), method: :delete, remote: true %>

app/views/foods/create.html.erb
<h1>Foods#create</h1>
<p>Find me in app/views/foods/create.html.erb</p>

app/views/foods/destroy.html.erb
<h1>Foods#destroy</h1>
<p>Find me in app/views/foods/destroy.html.erb</p>

app/views/foods/edit.html.erb
<h1>編集</h1>
<%= render "form" %>

app/views/foods/index.html.erb
<h1>お勧め料理 投稿一覧</h1>
<%= render @foods %>

app/views/foods/new.html.erb
<h1>新規投稿</h1>
<%= render "form" %>

app/views/foods/show.html.erb
<h1>投稿詳細</h1>
<p>【メールアドレス】 <%= @food.user.email %></p>
<p>【料理名】 <%= @food.name %></p>
<% if @food.image? %>
  <p><%= image_tag @food.image.url %></p>
<% end %>
<p>【コメント】 <%= simple_format h @food.comment %></p>
<p id="food-<%= @food.id %>">
  <% if @food.liked_by?(current_user) %>
    <%= render "like", food: @food %>
  <% else %>
    <%= render "dislike", food: @food %>
  <% end %>
</p>
<% if current_user.id == @food.user_id %>
  <p>
    <%= link_to "編集", edit_food_path(@food) %>
    <%= link_to "削除", food_path(@food), method: :delete, data: { confirm: "削除しますか？" } %>
  </p>
<% end %>
<p><%= link_to "投稿一覧へ", foods_path %></p>

app/views/foods/update.html.erb
<h1>Foods#update</h1>
<p>Find me in app/views/foods/update.html.erb</p>

app/views/layouts/_header.html.erb
<% if user_signed_in? %>
  <%= link_to "一覧ページ", root_path %>
  <%= link_to "新規投稿ページ", new_food_path %>
  <%= link_to "アカウント編集", edit_user_registration_path %>
  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, data: {confirm: "ログアウトしますか？"} %>
  <%= "【ログイン中のユーザーのアドレス】#{current_user.email}" %>
<% else %>
  <%= link_to "ログイン", new_user_session_path %>
  <%= link_to "アカウント登録", new_user_registration_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecommendedFoodApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render "layouts/header" %>
    </header>
    <hr>
    <%= yield %>
  </body>
</html>

app/views/likes/create.js.erb
document.getElementById('food-<%= @food.id %>').innerHTML = '<%= j render("foods/like", food: @food) %>'

app/views/likes/destroy.js.erb
document.getElementById('food-<%= @food.id %>').innerHTML = '<%= j render("foods/dislike", food: @food) %>'